<h3>Pandas DataFrame Experimentation: Basic Inspection

Data Source: https://www.kaggle.com/datasets/joycemara/european-fashion-store-multitable-dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load raw data csv:
campaigns_df = pd.read_csv('archive/dataset_fashion_store_campaigns.csv')
channels_df = pd.read_csv('archive/dataset_fashion_store_channels.csv')
customers_df = pd.read_csv('archive/dataset_fashion_store_customers.csv')
products_df = pd.read_csv('archive/dataset_fashion_store_products.csv')
sales_df = pd.read_csv('archive/dataset_fashion_store_sales.csv')
sale_items_df = pd.read_csv('archive/dataset_fashion_store_salesitems.csv')
stock_df = pd.read_csv('archive/dataset_fashion_store_stock.csv')

In [3]:
campaigns_df.head(10)

,campaign_id,campaign_name,start_date,end_date,channel,discount_type,discount_value
0,1,Spring Flash Sale,2025-04-01,2025-04-07,Email,Percentage,10.00%
1,2,Easter Promotion,2025-04-08,2025-04-15,Social Media,Fixed,10
2,3,Mother's Day Campaign,2025-05-01,2025-05-09,Email,Percentage,25.00%
3,4,Mid-Season Clearance,2025-05-10,2025-05-19,App Mobile,Percentage,30.00%
4,5,TIVA Week,2025-05-20,2025-05-31,Social Media,Percentage,30.00%
5,6,June Price Drop,2025-06-01,2025-06-09,Website Banner,Percentage,10.00%
6,7,Early Summer Deals,2025-06-10,2025-06-17,Email,Fixed,12

<h4>Summarize Data

In [4]:
campaigns_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   campaign_id     7 non-null      int64
 1   campaign_name   7 non-null      str
 2   start_date      7 non-null      str
 3   end_date        7 non-null      str
 4   channel         7 non-null      str
 5   discount_type   7 non-null      str
 6   discount_value  7 non-null      str
dtypes: int64(1), str(6)
memory usage: 524.0 bytes

In [5]:
campaigns_df.describe()

       campaign_id
count     7.000000
mean      4.000000
std       2.160247
min       1.000000
25%       2.500000
50%       4.000000
75%       5.500000
max       7.000000

In [6]:
campaigns_df.shape

(7, 7)

In [7]:
# Value counts for a given column
campaigns_df['discount_type'].value_counts()

discount_type
Percentage    5
Fixed         2
Name: count, dtype: int64

In [8]:
# Number of unique values of a given column
campaigns_df['campaign_name'].nunique()

7

In [9]:
# Datatype of the values in each column
campaigns_df.dtypes

campaign_id       int64
campaign_name       str
start_date          str
end_date            str
channel             str
discount_type       str
discount_value      str
dtype: object