<h3>Pandas DataFrame Experimentation: Reshaping

Data Source: https://www.kaggle.com/datasets/joycemara/european-fashion-store-multitable-dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load raw data csv:
campaigns_df = pd.read_csv('archive/dataset_fashion_store_campaigns.csv')
channels_df = pd.read_csv('archive/dataset_fashion_store_channels.csv')
customers_df = pd.read_csv('archive/dataset_fashion_store_customers.csv')
products_df = pd.read_csv('archive/dataset_fashion_store_products.csv')
sales_df = pd.read_csv('archive/dataset_fashion_store_sales.csv')
sale_items_df = pd.read_csv('archive/dataset_fashion_store_salesitems.csv')
stock_df = pd.read_csv('archive/dataset_fashion_store_stock.csv')

<h4>Group Data

In [17]:
stock_df

     country  product_id  stock_quantity
0     France           1              61
1     France           2              24
2     France           3              81
3     France           4              70
4     France           5              30
..       ...         ...             ...
995  Germany         496               1
996  Germany         497               1
997  Germany         498               1
998  Germany         499               1
999  Germany         500               1

[1000 rows x 3 columns]

In [16]:
stock_df['country'].nunique()

2

In [21]:
stock_by_country = stock_df.groupby('country', as_index=False)['stock_quantity'].sum()
stock_by_country

   country  stock_quantity
0   France           24136
1  Germany             500